// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To update this file, edit the Firebase connection details in Studio.

import type { FirebaseOptions } from 'firebase/app';

// This configuration is public and can be safely shared with clients.
// It's used to initialize the Firebase app on the client side.
// Security is enforced by Firebase Security Rules.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
};
